name: Multi-Runner Python Test

on:
  workflow_dispatch:

jobs:
  run-legacy-python:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Verify Python 2.7
        run: |
          echo "Running on Python 2.7..."
          python2 --version

  run-latest-python:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Verify Python Latest
        run: |
          echo "Running on Python 3..."
          python3 --version
